steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--no-cache', '--rm=true', '--tag', 'gcr.io/$PROJECT_ID/atlassian-jira-software', '--tag', 'gcr.io/$PROJECT_ID/atlassian-jira-software:7.4.0', '.']

images: ['gcr.io/$PROJECT_ID/atlassian-jira-software']
